heat_template_version: '2013-05-23'

parameters:
  param_content:
    default: "Arbor:Amazing"
    description: "Param Injection Content"
    type: string

resources:
  compute_instance:
    type: OS::Nova::Server
    properties:
      flavor: 4 GB Performance
      image: 7fd88211-ce43-41bf-9a85-e73df4066581 # CoreOS
      config_drive: true
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            write_files:
            - path: /tmp/testfile
              owner: root
              permissions: 0644
              content: |
                {param_inject}
          params:
            param_inject: {get_param: param_content}
