heat_template_version: '2013-05-23'

resources:
  compute_instance:
    type: OS::Nova::Server
    properties:
      flavor: 4 GB Performance
      image: 7fd88211-ce43-41bf-9a85-e73df4066581 # CentOS
      personality: {/tmp/testfile: testfile}