heat_template_version: '2013-05-23'

parameters:

  param_content:
    default: "Arbor:Amazing"
    description: "Param Injection Content"
    type: string

  name:
    default: CoreOS-stable
    description: "Name of each CoreOS machine booted"
    type: string

  docker_run:
    type: string
    default: "docker run -p 80:5000 -d 23.253.106.198:5042/nodeus-1"

resources:
  compute_instance:
    type: OS::Nova::Server
    properties:
      flavor: 4 GB Performance
      image: 7fd88211-ce43-41bf-9a85-e73df4066581 # CoreOS
      name:
        str_replace:
          template: stack-compute-instance
          params:
            stack: { get_param: "OS::stack_name" }
      config_drive: true
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            docker run -p 80:5000 -d 23.253.106.198:5042/nodeus-1
            touch /tmp/testfile
            echo param_inject > /tmp/testfile
            chmod 0644 /tmp/testfile
          params:
            param_inject: {get_param: param_content}

  lb:
    type: Rackspace::Cloud::LoadBalancer
    properties:
      name:
        str_replace:
          template: Stack Compute Load Balancer
          params:
            "Stack": { get_param: "OS::stack_name" }
      nodes:
      - addresses: [ { get_attr: [compute_instance, networks, private, 0] } ]
        port: 80
        condition: ENABLED
      protocol: HTTP
      port: 80
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4

outputs:
  "Load Balancer IP":
    value: { get_attr: [ lb, PublicIp ] }
    description: Load Balancer IP
