heat_template_version: 2013-05-23

description: |
  Testing Docker resource

resources:

  ##################################
  # CoreOS host for the containers #
  ##################################

  container_host:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
            template: stackname-container-host
            params:
                stackname: { get_param: "OS::stack_name" }
      image: CoreOS (Stable)
      flavor: 4 GB Performance
      admin_pass: password
      config_drive: true
      user_data_format: RAW
      # Expose the docker rest API on the CoreOS machine (not secure)
      # user data copied from:
      # https://coreos.com/docs/launching-containers/building/customizing-docker/
      # #enable-the-remote-api-on-a-new-socket
      user_data: |
        #cloud-config
        coreos:
          units:
          - name: docker-tcp.socket
            command: start
            enable: yes
            content: |
              [Unit]
              Description=Docker Socket for the API

              [Socket]
              ListenStream=2375
              BindIPv6Only=both
              Service=docker.service

              [Install]
              WantedBy=sockets.target
          - name: enable-docker-tcp.service
            command: start
            content: |
              [Unit]
              Description=Enable the Docker Socket for the API

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/systemctl enable docker-tcp.socket
          - name: my.service
            command: start
            enable: true
            content: |
              [Unit]
              Description=my-service
              After=docker.service
              Requires=docker.service

              [Service]
              TimeoutStartSec=0
              ExecStartPre=-/usr/bin/docker kill my
              ExecStartPre=-/usr/bin/docker rm my
              ExecStartPre=/usr/bin/docker pull me/myrepo
              ExecStart=/usr/bin/docker run --name my me/myrepo
              ExecStop=/usr/bin/docker stop my
        write_files:
          - path: /home/core/.dockercfg
            permissions: '0644'
            owner: root:root
            content: |
              {
              "http://23.253.106.198:5042": {
              "auth": "c2FiZWVuOnNhYmVlbjEyMw==",
              "email": "sabeen.syed@rackspace.com"}
              }
##########################################################################################
# Enable alternative repositories example: https://coreos.com/docs/launching-
# containers/building/customizing-docker/#using-a-dockercfg-file-for-authentication
#        write_files:
#          - path: /home/core/.dockercfg
#            owner: core:core
#            permissions: 0644
#            content: |
#            {
#              "https://index.docker.io/v1/": {
#              "auth": "xXxXxXxXxXx=",
#              "email": "username@example.com"
#            },
#              "https://index.example.com": {
#              "auth": "XxXxXxXxXxX=",
#              "email": "username@example.com"
#            }
#            }
##########################################################################################


  ############################################
  # Docker Container                          #
  #  #
  ############################################

  solum_container:
    type: DockerInc::Docker::Container
    properties:
      name: solum-container
      image: nodeus-1
      docker_endpoint:
        str_replace:
          template: "host:2375"
          params:
            host: { get_attr: [ container_host, accessIPv4 ] }

outputs:
  solum_status:
    description: Status
    value: { get_attr: [ solum_container, info, State ] }