heat_template_version: 2013-05-23

description: |
  Testing Docker resource

resources:

  ##################################
  # CoreOS host for the container #
  ##################################

  container_host:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
            template: stackname-container-host
            params:
                stackname: { get_param: "OS::stack_name" }
      image: CoreOS (Stable)
      flavor: 4 GB Performance
      admin_pass: password
      config_drive: true
      user_data_format: RAW
      # Expose the docker rest API on the CoreOS machine (not secure)
      # user data copied from:
      # https://coreos.com/docs/launching-containers/building/customizing-docker/
      # #enable-the-remote-api-on-a-new-socket
      user_data: |
        #cloud-config
        write_files:
          - path: /home/core/.dockercfg
            permissions: core:core
            owner: root
            content: |
              [Service]
                User=core
              {
              "23.253.106.198:5042/nodeus-1"
              }
        coreos:
          units:
          - name: docker-tcp.socket
            command: start
            enable: yes
            content: |
              [Unit]
              Description=Docker Socket for the API

              [Socket]
              ListenStream=2375
              BindIPv6Only=both
              Service=docker.service

              [Install]
              WantedBy=sockets.target
          - name: enable-docker-tcp.service
            command: start
            content: |
              [Unit]
              Description=Enable the Docker Socket for the API

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/systemctl enable docker-tcp.socket

  ############################################
  # Nodeus-1 Container                          #
  ############################################

  solum_container:
    type: DockerInc::Docker::Container
    properties:
      name: solum-container
      image: nodeus-1
      port_bindings:
        80/tcp:
          HostPort: 80
      port_specs:
      - "5000"
      docker_endpoint:
        str_replace:
          template: "host:2375"
          params:
            host: { get_attr: [ container_host, accessIPv4 ] }
      #hostname: 23.253.106.198:5042

outputs:

  ####################################################
  # Output #
  #                                    #
  ####################################################

  solum_curl:
    description: solum
    value:
      str_replace:
        template: "curl address"
        params:
          address: { get_attr: [ container_host, accessIPv4 ] }
