heat_template_version: 2013-05-23

parameters:
  count:
    type: number

resources:
  web_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: OS::Nova::Server
        properties:
          flavor: 1GB Standard Instance
          image: 7fd88211-ce43-41bf-9a85-e73df4066581
          name: LB-Compute Web Nodes
        user_data:
          str_replace:
            params:
              count:
                get_param: count
            template: |
                #!/bin/bash -x
                # Invoke the container
                docker run -p 80:5000 -d 23.253.106.198:5042/nodeus-1
        #user_data_format: RAW

  lb:
    type: Rackspace::Cloud::LoadBalancer
    properties:
      name: LB-Compute Load Balancer
      nodes:
      - addresses: { get_attr: [web_nodes, accessIPv4]} # This is where the
                                                       # wiring magic happens
        port: 80
        condition: ENABLED
      healthMonitor:
        attemptsBeforeDeactivation: 3
        delay: 10
        timeout: 120
        type: HTTP
        path: "/"
        statusRegex: "."
        bodyRegex: "."
      protocol: HTTP
      port: 80
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4

outputs:
  lb_public_ip:
    description: The public IP address of the load balancer
    value: { get_attr: [lb, PublicIp]}
